<?php
namespace Database\Seeders;

use App\Models\District;
use Illuminate\Database\Seeder;

class DistrictsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $district_ars = [
            ['name'                => 'Bagerhat',
                'police_station_names' => [
                    'Bagerhat Sadar',
                    'Chitalmari',
                    'Fakirhat',
                    'Kachua',
                    'Mollahat',
                    'Morrelganj',
                    'Rampal',
                    'Sadar Upazila',
                    'Sharankhola',
                ],
            ],
            ['name'                => 'Bandarban',
                'police_station_names' => [
                    'Bandarban Sadar',
                    'Lama',
                    'Rowangchhari',
                    'Ruma',
                    'Thanchi',
                    'Alikadam',
                    'Naikhongchhari',
                ],
            ],
            [
                'name'                 => 'Barguna',
                'police_station_names' => [
                    'Amtali',
                    'Bamna',
                    'Barguna Sadar',
                    'Betagi',
                    'Patharghata',
                    'Taltali',
                ],
            ],
            [
                'name'                 => 'Barisal',
                'police_station_names' => [
                    'Agailjhara',
                    'Babuganj',
                    'Bakerganj',
                    'Banaripara',
                    'Barisal Sadar',
                    'Gournadi',
                    'Hizla',
                    'Mehendiganj',
                    'Muladi',
                    'Wazirpur',
                ],
            ]
            ,
            [
                'name'                 => 'Bhola',
                'police_station_names' => [
                    'Bhola Sadar',
                    'Burhanuddin',
                    'Char Fasson',
                    'Daulatkhan',
                    'Lalmohan',
                    'Manpura',
                    'Tazumuddin',
                ],
            ],
            [
                'name'                 => 'Bogra',
                'police_station_names' => [
                    'Adamdighi',
                    'Bogra Sadar',
                    'Dhunat',
                    'Dhupchanchia',
                    'Gabtali',
                    'Kahaloo',
                    'Nandigram',
                    'Sariakandi',
                    'Shajahanpur',
                    'Sherpur',
                    'Shibganj',
                    'Sonatala',
                ],
            ],
            ['name' => 'Brahmanbaria', 'police_station_names' => [
                'Ashuganj',
                'Bancharampur',
                'Brahmanbaria Sadar',
                'Kasba',
                'Nabinagar',
                'Nasirnagar',
                'Sarail',
                'Bijoynagar',
            ]],
            ['name' => 'Chandpur', 'police_station_names' => [
                'Chandpur Sadar',
                'Faridganj',
                'Haimchar',
                'Haziganj',
                'Kachua',
                'Matlab North',
                'Matlab South',
                'Shahrasti',
            ]],
            ['name' => 'Chapai Nawabganj', 'police_station_names' => [
                'Bholahat',
                'Gomastapur',
                'Nachole',
                'Nawabganj Sadar',
                'Shibganj',
            ]],
            ['name' => 'Chattogram', 'police_station_names' => [
                'Anwara',
                'Banshkhali',
                'Boalkhali',
                'Chandanaish',
                'Fatikchhari',
                'Hathazari',
                'Lohagara',
                'Mirsharai',
                'Patiya',
                'Rangunia',
                'Raozan',
                'Sandwip',
                'Satkania',
                'Sitakunda',
            ]],
            ['name' => 'Chuadanga', 'police_station_names' => [
                'Chuadanga Sadar',
                'Alamdanga',
                'Damurhuda',
                'Jibannagar',
            ]],
            ['name' => 'Comilla', 'police_station_names' => [
                'Comilla Kotwali',
                'Debidwar',
                'Muradnagar',
                'Homna',
                'Titas',
                'Meghna',
                'Daudkandi',
                'Chandina',
                'Barura',
                'Laksam',
                'Brahmanpara',
                'Monohorgonj',
                'Nangalkot',
                'Burichang',
                'Lalmai',
                'Chouddagram',
            ]],
            ['name' => 'Cox’s Bazar', 'police_station_names' => [
                'Cox’s Bazar Sadar',
                'Ramu',
                'Chakaria',
                'Pekua',
                'Kutubdia',
                'Maheshkhali',
                'Teknaf',
                'Ukhia',
            ]],
            ['name' => 'Dhaka', 'police_station_names' => [
                'Dhanmondi',
                'Gulshan',
                'Banani',
                'Mirpur',
                'Tejgaon',
                'Mohammadpur',
                'Paltan',
                'Motijheel',
                'Shahbagh',
                'Ramna',
                'Lalbagh',
                'Kotwali',
                'Uttara',
                'Airport',
                'Badda',
                'Cantonment',
                'Khilgaon',
                'Khilkhet',
                'Jatrabari',
                'Demra',
                'Sabujbagh',
                'Turag',
                'Hazaribagh',
                'New Market',
                'Wari',
                'Shyampur',
            ]],
            ['name' => 'Dinajpur', 'police_station_names' => [
                'Dinajpur Sadar',
                'Birampur',
                'Birganj',
                'Biral',
                'Bochaganj',
                'Chirirbandar',
                'Fulbari',
                'Ghoraghat',
                'Hakimpur',
                'Khansama',
                'Nawabganj',
                'Parbatipur',
            ]],
            ['name' => 'Faridpur', 'police_station_names' => [
                'Faridpur Sadar',
                'Boalmari',
                'Alfadanga',
                'Madhukhali',
                'Bhanga',
                'Nagarkanda',
                'Charbhadrasan',
                'Saltha',
                'Sadarpur',
            ]],
            ['name' => 'Feni', 'police_station_names' => [
                'Feni Sadar',
                'Chhagalnaiya',
                'Parshuram',
                'Fulgazi',
                'Daganbhuiyan',
                'Sonagazi',
            ]],
            ['name' => 'Gaibandha', 'police_station_names' => [
                'Gaibandha Sadar',
                'Gobindaganj',
                'Sundarganj',
                'Palashbari',
                'Sadullapur',
                'Saghata',
                'Fulchhari',
            ]],
            ['name' => 'Gazipur', 'police_station_names' => [
                'Gazipur Sadar',
                'Tongi',
                'Kaliakair',
                'Kapasia',
                'Sreepur',
            ]],
            ['name' => 'Gopalganj', 'police_station_names' => [
                'Gopalganj Sadar',
                'Kashiani',
                'Kotalipara',
                'Muksudpur',
                'Tungipara',
            ]],
            ['name' => 'Habiganj', 'police_station_names' => [
                'Habiganj Sadar',
                'Ajmeriganj',
                'Baniachong',
                'Chunarughat',
                'Madhabpur',
                'Nabiganj',
                'Lakhai',
                'Shaistaganj',
            ]],
            ['name' => 'Jamalpur', 'police_station_names' => [
                'Jamalpur Sadar',
                'Islampur',
                'Melandaha',
                'Jadunathpur',
                'Baksiganj',
                'Dewanganj',
                'Sharishabari',
            ]],
            ['name' => 'Jashore', 'police_station_names' => [
                'Jashore Sadar',
                'Abhaynagar',
                'Keshabpur',
                'Chougachha',
                'Bagherpara',
                'Sharshel',
                'Monirampur',
                'Manirampur',
            ]],
            ['name' => 'Jhalokati', 'police_station_names' => [
                'Jhalokati Sadar',
                'Kathalia',
                'Rajapur',
                'Nalchity',
                'Barisal',
                'Rupatali',
            ]],
            ['name' => 'Jhenaidah', 'police_station_names' => [
                'Jhenaidah Sadar',
                'Kaliganj',
                'Shailkupa',
                'Kotchandpur',
                'Harinarayanpur',
                'Chuadanga',
                'Manirampur',
                'Mohammadpur',
            ]],
            ['name' => 'Joypurhat', 'police_station_names' => [
                'Joypurhat Sadar',
                'Khetlal',
                'Akkelpur',
                'Panchbibi',
                'Kalai',
            ]],
            ['name' => 'Khagrachari', 'police_station_names' => [
                'Khagrachari Sadar',
                'Dighinala',
                'Lakshmipur',
                'Mahalchhari',
                'Manikchhari',
                'Matiranga',
                'Murtizapur',
            ]],
            ['name' => 'Khulna', 'police_station_names' => [
                'Khulna Sadar',
                'Koyra',
                'Dacope',
                'Rupsha',
                'Bagerhat',
                'Paikgachha',
                'Kolatoli',
                'Terokhada',
            ]],
            ['name' => 'Kishoreganj', 'police_station_names' => [
                'Kishoreganj Sadar',
                'Karimganj',
                'Kuliarchar',
                'Hossainpur',
                'Itna',
                'Bajitpur',
                'Nikli',
                'Pakundia',
            ]],
            ['name' => 'Kurigram', 'police_station_names' => [
                'Kurigram Sadar',
                'Bhurungamari',
                'Chilmari',
                'Nageswari',
                'Rajibpur',
                'Ranishankoil',
                'Ulipur',
            ]],
            ['name' => 'Kushtia', 'police_station_names' => [
                'Kushtia Sadar',
                'Kumarkhali',
                'Mirpur',
                'Khoksa',
                'Bheramara',
                'Daulatpur',
            ]],
            ['name' => 'Lakshmipur', 'police_station_names' => [
                'Lakshmipur Sadar',
                'Raipur',
                'Ramganj',
                'Lohagara',
                'Kamolnagar',
            ]],
            ['name' => 'Lalmonirhat', 'police_station_names' => [
                'Lalmonirhat Sadar',
                'Aditmari',
                'Khalisha Chapani',
                'Hatibandha',
                'Patgram',
            ]],
            ['name' => 'Madaripur', 'police_station_names' => [
                'Madaripur Sadar',
                'Shibchar',
                'Kalkini',
                'Rajoir',
            ]],
            ['name' => 'Magura', 'police_station_names' => [
                'Magura Sadar',
                'Sreepur',
                'Shalikha',
                'Madhupur',
            ]],
            ['name' => 'Manikganj', 'police_station_names' => [
                'Manikganj Sadar',
                'Singair',
                'Shibalaya',
                'Daulatpur',
                'Harirampur',
            ]],
            ['name' => 'Meherpur', 'police_station_names' => [
                'Meherpur Sadar',
                'Mujibnagar',
                'Kusumgram',
                'Gangni',
            ]],
            ['name' => 'Moulvibazar', 'police_station_names' => [
                'Moulvibazar Sadar',
                'Kulaura',
                'Juri',
                'Barlekha',
                'Rajnagar',
                'Komlanghat',
            ]],
            ['name' => 'Munshiganj', 'police_station_names' => [
                'Munshiganj Sadar',
                'Sreenagar',
                'Tongibari',
                'Madaripur',
                'Chandpur',
            ]],
            ['name' => 'Mymensingh', 'police_station_names' => [
                'Mymensingh Sadar',
                'Trishal',
                'Muktagacha',
                'Bhaluka',
                'Gaffargaon',
            ]],
            ['name' => 'Naogaon', 'police_station_names' => [
                'Naogaon Sadar',
                'Raninagar',
                'Manda',
                'Atrai',
                'Dhamuirhat',
                'Mahadevpur',
            ]],
            ['name' => 'Narail', 'police_station_names' => [
                'Narail Sadar',
                'Kalia',
                'Lohagara',
            ]],
            ['name' => 'Narayanganj', 'police_station_names' => [
                'Narayanganj Sadar',
                'Sonargaon',
                'Rupganj',
                'Araihazar',
            ]],
            ['name' => 'Narsingdi', 'police_station_names' => [
                'Narsingdi Sadar',
                'Raipura',
                'Belabo',
                'Monohardi',
                'Shibpur',
            ]],
            ['name' => 'Natore', 'police_station_names' => [
                'Natore Sadar',
                'Lalpur',
                'Bagatipara',
                'Baraigram',
                'Gurudaspur',
            ]],
            ['name' => 'Netrokona', 'police_station_names' => [
                'Netrokona Sadar',
                'Atpara',
                'Kendua',
                'Durgapur',
                'Khaliajuri',
                'Mohanganj',
            ]],
            ['name' => 'Nilphamari', 'police_station_names' => [
                'Nilphamari Sadar',
                'Domar',
                'Jaldhaka',
                'Kishoreganj',
                'Syedpur',
            ]],
            ['name' => 'Noakhali', 'police_station_names' => [
                'Noakhali Sadar',
                'Begumganj',
                'Chatkhil',
                'Haimchar',
                'Senbagh',
                'Companiganj',
            ]],
            ['name' => 'Pabna', 'police_station_names' => [
                'Pabna Sadar',
                'Bera',
                'Faridpur',
                'Ishwardi',
                'Atghoria',
                'Santhia',
            ]],
            ['name' => 'Panchagarh', 'police_station_names' => [
                'Panchagarh Sadar',
                'Boda',
                'Debiganj',
                'Atwari',
                'Tetulia',
            ]],
            ['name' => 'Patuakhali', 'police_station_names' => [
                'Patuakhali Sadar',
                'Galachipa',
                'Dumki',
                'Mirzaganj',
                'Bauphal',
            ]],
            ['name' => 'Pirojpur', 'police_station_names' => [
                'Pirojpur Sadar',
                'Kochua',
                'Nesarabad',
                'Indurkani',
                'Kaliakair',
            ]],
            ['name' => 'Rajbari', 'police_station_names' => [
                'Rajbari Sadar',
                'Goalanda',
                'Pangsha',
                'Baira',
                'Madaripur',
            ]],
            ['name' => 'Rajshahi', 'police_station_names' => [
                'Rajshahi Sadar',
                'Godagari',
                'Paba',
                'Bagmara',
                'Durgapur',
                'Charghat',
            ]],
            ['name' => 'Rangamati', 'police_station_names' => [
                'Rangamati Sadar',
                'Kaptai',
                'Baghaichhari',
                'Kawkhali',
                'Barkal',
                'Juraichhari',
            ]],
            ['name' => 'Rangpur', 'police_station_names' => [
                'Rangpur Sadar',
                'Pirganj',
                'Gangachara',
                'Kaunia',
                'Mithapukur',
                'Badarganj',
                'Pirgachha',
            ]],
            ['name' => 'Satkhira', 'police_station_names' => [
                'Satkhira Sadar',
                'Kaliganj',
                'Assasuni',
                'Shyamnagar',
                'Debhata',
                'Tala',
            ]],
            ['name' => 'Shariatpur', 'police_station_names' => [
                'Shariatpur Sadar',
                'Zanjira',
                'Naria',
                'Bhedarganj',
                'Gosairhat',
            ]],
            ['name' => 'Sherpur', 'police_station_names' => [
                'Sherpur Sadar',
                'Nalitabari',
                'Jhenaigati',
                'Sreebardi',
                'Nakla',
            ]],
            ['name' => 'Sirajganj', 'police_station_names' => [
                'Sirajganj Sadar',
                'Chauhali',
                'Kazamganj',
                'Shahjadpur',
                'Kamarkhanda',
            ]],
            ['name' => 'Sunamganj', 'police_station_names' => [
                'Sunamganj Sadar',
                'Chhatak',
                'Dakkhin Sunamganj',
                'Jamalganj',
                'Tahirpur',
            ]],
            ['name' => 'Sylhet', 'police_station_names' => [
                'Sylhet Sadar',
                'Moulvibazar',
                'Fenchuganj',
                'Jaintapur',
                'Kanaighat',
            ]],
            ['name' => 'Tangail', 'police_station_names' => [
                'Tangail Sadar',
                'Kalihati',
                'Nagarpur',
                'Mirzapur',
                'Bhuapur',
            ]],
            ['name' => 'Thakurgaon', 'police_station_names' => [
                'Thakurgaon Sadar',
                'Pirganj',
                'Ranishankail',
                'Baliadangi',
                'Haripur',
            ]],
        ];

        foreach ($district_ars as $district_ar) {
            $district = District::create([
                'name' => $district_ar['name'],
            ]);

            if (isset($district_ar['police_station_names']) && is_array($district_ar['police_station_names'])) {
                foreach ($district_ar['police_station_names'] as $police_station_name) {
                    $district->policeStations()->create([
                        'name' => $police_station_name,
                    ]);
                }
            }

        }
    }
}
